### ISSUE TITLE
Not exporting context

### ISSUE THREAD

**Issue by hendrul** [wilsonlewis/require-context#3]
Mismatch between readme and actual API?
In the docs you said I could do...
```js
require.context('./menues', false, /\.\/menu(\d+)\.jsx?$/i)
```
But you are not exporting context

**Comment by wilsonlewis** [comment]
I'm not sure what you are asking - can you give me an example of exactly what you are trying to do?

Thanks!

**Comment by radcapitalist** [comment]
Maybe I can help.  I think what @hendrul is saying is that if you follow the instructions provided in the readme, it doesn't work.  When node.js sees "require.context", it complains "TypeError: require.context is not a function."  At least, that is my experience. 

I'm at Node.js version 10.15.1.  I've tried placing this line in a couple places:

`require('require-context/register');`

(Does the above line belong in the .js file where you're trying to use **require.context()**  or in a .js file that gets required in **before** the .js file where **require.context()** is used?)

Nothing I've tried has caused **require.context()** to not throw the above TypeError.

I added the second "require" from the readme:

`var requireContext = require('require-context');`

without seeing how it could help **require.context()** be found, and it didn't, so I changed the line of code calling **require.context()** to call **requireContext()** instead.  Which eliminated the TypeError, but what does this solve, because webpack will be looking for **require.context()**?

Also, when I put this line in my startup file:

`require('require-context/register');`

I got strange errors like this one from other modules:

```
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:404:5)
```

With 6000 downloads a week, somebody is clearly getting value from this module, but for the life of me I can't figure it out.

Thanks,

Eric
